Manual update changes
openzim/wp1 pull request #284
Opened 2021-03-17 20:19 UTC by mahakporwal02

new manual update not starting until previous update in progress.
This resolves #186

2021-03-17 21:06 UTC, mahakporwal02 commented
@audiodude Sorry, there was issue with my local repository therefore I had to force-push the code multiple times.
I have added conditions to `manual update button` so that it would not show while the update is ongoing.
Also after one hour and when update is not yet completed, the `update time`  becomes `null` so I have added the extra paragraph.

2021-03-17 23:51 UTC, audiodude requested changes

2021-03-17 23:51 UTC, audiodude commented on wp1-frontend/src/components/UpdatePage.vue
>              <b>{{ updateTime }}</b
I would prefer if this was all one paragraph. Something like "The next update can be performed at {{ updateTime }} or when the current update completes, whichever is later."

2021-03-17 23:51 UTC, audiodude commented on wp1-frontend/src/components/UpdatePage.vue
> +        <div v-if="currentProject && !updateTime && (!jobScheduled || jobComplete)">
Doesn't the status enum contain an "in_progress" value or something similar that we can check for. This is a roundabout way of saying that.

2021-03-17 23:51 UTC, audiodude commented on wp1-frontend/src/components/Autocomplete.vue
> +        <b>Note: This tool can only perform manual updates once per hour only after current update is completed.</b>
"...once per hour at most. It also cannot perform an update until all pending updates are complete."

2021-03-18 05:50 UTC, mahakporwal02 commented on wp1-frontend/src/components/UpdatePage.vue
>              <b>{{ updateTime }}</b
If the job is not completed but update time has become null (its been over an hour) so it would show something like this:
(I have made some changes in front-end for this screenshot.)
![manual update](https://user-images.githubusercontent.com/56486682/111579171-89895b00-87db-11eb-9e47-87cd34b922f6.png)

2021-03-18 05:52 UTC, mahakporwal02 commented on wp1-frontend/src/components/UpdatePage.vue
> +        <div v-if="currentProject && !updateTime && (!jobScheduled || jobComplete)">
@audiodude In the original code same format is used to show in_progress status please have a look at line 51.
![manual update progress](https://user-images.githubusercontent.com/56486682/111578999-2a2b4b00-87db-11eb-9b78-14cdf61d1630.png)

2021-03-18 06:00 UTC, audiodude commented on wp1-frontend/src/components/UpdatePage.vue
> +        <div v-if="currentProject && !updateTime && (!jobScheduled || jobComplete)">
Fair enough.

2021-03-18 06:02 UTC, audiodude commented on wp1-frontend/src/components/UpdatePage.vue
>              <b>{{ updateTime }}</b
Right, but what I don't like is two paragraphs with almost identical text. You should either strive to have one explanation that works in both cases, or minimize your v-if block so that it covers only the part of the text that is changing.

2021-03-18 06:03 UTC, audiodude commented on wp1-frontend/src/components/Autocomplete.vue
> +        <b>Note: This tool can only perform manual updates once per hour only after current update is completed.</b>
Can you change the text to what I specified?

2021-03-18 06:24 UTC, mahakporwal02 commented on wp1-frontend/src/components/Autocomplete.vue
> +        <b>Note: This tool can only perform manual updates once per hour only after current update is completed.</b>
Yes sir, already done
Thanks

2021-03-18 06:46 UTC, mahakporwal02 commented on wp1-frontend/src/components/UpdatePage.vue
>              <b>{{ updateTime }}</b
Done, pls have a look at new changes.

2021-03-18 07:35 UTC, audiodude approved these changes
LGTM, thanks!

2021-03-18 07:35 UTC, merged

2021-03-18 07:36 UTC, audiodude commented
I'll try to remember to deploy this and the other change tomorrow morning.

2021-03-18 08:06 UTC, mahakporwal02 commented
OK, thanks