cypress test for project-table
openzim/wp1 pull request #286
Opened 2021-03-21 15:22 UTC by mahakporwal02

Added cypress integeration test for appropriate table being displayed after user clicks on a particular option.

2021-03-21 17:43 UTC, audiodude requested changes
For the codefactor issues, I would try implementing this SO answer: https://stackoverflow.com/a/60154342/41060

Your test also isn't passing on CI: https://travis-ci.com/github/openzim/wp1/jobs/492621989#L395

Were you able to run it locally?

2021-03-21 17:43 UTC, audiodude commented on wp1-frontend/cypress/integration/home_page.spec.js
> +  it('project-table for Alien displayed', () => {
I would put this test case inside of the describe block for "the home page" because it's testing something on the home page. Generally, all the tests in one spec.js file will be in a master describe block, with sub-describe blocks for individual areas.

2021-03-21 18:18 UTC, audiodude commented on wp1-frontend/cypress/integration/home_page.spec.js
> +  it('project-table for Alien displayed', () => {
Okay I just patched your PR and tried the tests locally and they pass locally. So it must be timing out because the docker server is too slow in CI.

2021-03-21 18:19 UTC, audiodude commented
> Were you able to run it locally?

Okay I just patched your PR and tried the tests locally and they pass locally. So it must be timing out because the docker server is too slow in CI.

2021-03-21 19:20 UTC, mahakporwal02 commented on wp1-frontend/cypress/integration/home_page.spec.js
> +  it('project-table for Alien displayed', () => {
@audiodude Do you mean I should make a new file and add this code in it?

2021-03-21 19:29 UTC, audiodude commented on wp1-frontend/cypress/integration/home_page.spec.js
> +  it('project-table for Alien displayed', () => {
No, just that it should be part of the `describe` block above. So like the other `it` declarations in this file, it should be part of the function passed to `describe('the home page', ...`

2021-03-21 19:47 UTC, kelson42 commented
Two small remarks:
* We migrate all our ptojects from Travis CI to Github Actions. One of the advantages is that it is more reliable
* We try to use more and more the Github Docker repository because it does not have such limitations like Docker hub.

2021-03-22 09:03 UTC, mahakporwal02 commented on wp1-frontend/cypress/integration/home_page.spec.js
> +  it('project-table for Alien displayed', () => {
I think it is part of describe('the home page') block like other it declarations.

2021-03-23 02:10 UTC, audiodude commented on wp1-frontend/cypress/integration/home_page.spec.js
> +  it('project-table for Alien displayed', () => {
Yes you're right.

2021-03-23 02:11 UTC, audiodude commented
@kelson42 So should we hold off on this PR until we can migrate to Github Actions? What limitations of Docker hub are you referring to? Docker hub doesn't seem to be the issue here.

2021-03-25 07:08 UTC, audiodude commented
@mahakporwal02  Can you push a new commit here and see if the new CI with GIthub Actions picks it up and if it passes? Thanks!

2021-03-25 13:11 UTC, mahakporwal02 commented
@audiodude I don't get why cypress test is failing, They are running fine locally. Please have a look.
![Screenshot from 2021-03-25 13-28-18](https://user-images.githubusercontent.com/56486682/112478060-98eb4400-8d99-11eb-91ef-9f16e8f7e598.png)

2021-03-25 16:30 UTC, audiodude commented
I'm not sure why it's failing either, my initial guess was that it was timing out somehow in Travis CI, but we're now seeing the same (mis)behavior in Github actions.

I've submitted #297 to upload the videos and screenshots from Cypress runs. Can you try merging with master and pushing the code again to see what artifacts we get from Cypress?

2021-03-25 19:57 UTC, mahakporwal02 commented
> I'm not sure why it's failing either, my initial guess was that it was timing out somehow in Travis CI, but we're now seeing the same (mis)behavior in Github actions.
> 
> I've submitted #297 to upload the videos and screenshots from Cypress runs. Can you try merging with master and pushing the code again to see what artifacts we get from Cypress?
> 
> EDIT: Actually I was able to re-run CI myself, let's see if it picks up my upload changes.
> EDIT 2: No it didn't pick up the upload changes, can you try merging master like I suggested?

Done, please check it.

2021-03-26 01:45 UTC, audiodude commented
@mahakporwal02 Can you try merging master again? I made a change to the workflow so that it always uploads the artifacts even if the test fails (#300). Currently it's bailing on the upload because the previous step failed.

2021-03-26 06:00 UTC, mahakporwal02 commented
> @mahakporwal02 Can you try merging main again? I made a change to the workflow so that it always uploads the artifacts even if the test fails (#300). Currently it's bailing on the upload because the previous step failed.

Done.

2021-03-26 07:07 UTC, kelson42 commented
> @kelson42 So should we hold off on this PR until we can migrate to Github Actions? What limitations of Docker hub are you referring to? Docker hub doesn't seem to be the issue here.

I let you decide this. Does not seem to be a bad approach to me. The problem with Docker hub are:
* Its relative lack of stability
* Its newly limitation/quota in terme of pull

Perfectly possible you are not impacted here.

2021-03-26 17:43 UTC, audiodude commented
So by looking at the video and screenshot, it seems clear that the call is simply timing out.

I was going to suggest adding a `cy.wait()` command here but [the documentation](https://docs.cypress.io/guides/references/best-practices#Unnecessary-wait-for-cy-get) strongly recommends against it. So we should instead use the pattern that they suggest, intercepting the call to /table and waiting on that.

2021-03-26 18:17 UTC, audiodude commented
I'm going to cherrypick the Codefactor fix into the main branch so that all of these PRs don't suffer from it. Thanks for that!

2021-03-26 18:18 UTC, mahakporwal02 commented
> So by looking at the video and screenshot, it seems clear that the call is simply timing out.
> 
> I was going to suggest adding a `cy.wait()` command here but [the documentation](https://docs.cypress.io/guides/references/best-practices#Unnecessary-wait-for-cy-get) strongly recommends against it. So we should instead use the pattern that they suggest, intercepting the call to /table and waiting on that.

cy.intercept doesn't run in current version of cypress.Should I update it then?

2021-03-26 18:22 UTC, audiodude commented
> cy.intercept doesn't run in current version of cypress.Should I update it then?

Yes let's update it, but as a separate issue and PR. I think the cy.intercept() changes are the main differences between Cypress 5 (which we're on) and 6 (which we'll go to). And since we don't use it yet, it should be a smooth upgrade.

2021-03-27 14:20 UTC, mahakporwal02 commented
@audiodude I am stuck on cy.wait() part. Pls have a look.
![Screenshot from 2021-03-27 19-46-50](https://user-images.githubusercontent.com/56486682/112723633-99204680-8f35-11eb-83d2-364414b0fa49.png)
![Screenshot from 2021-03-27 19-47-02](https://user-images.githubusercontent.com/56486682/112723634-9a517380-8f35-11eb-8d18-3b8f6054ed14.png)

2021-03-27 19:19 UTC, audiodude commented
@mahakporwal02 You want to intercept the project table call. Intercept is used for spying on or mocking XHR calls that the page makes. So here you would want to spy on the call to the backend, `/v1/projects/Alien/table`:

<img width="453" alt="Screen Shot 2021-03-27 at 12 17 47 PM" src="https://user-images.githubusercontent.com/57832/112732340-994d2180-8ef6-11eb-98de-43f7195a50e8.png">

You should probably match on the string `'/v1/projects/Alien/table'` instead of the full url, so that the test doesn't break if the backend port changes for any reason.

Hope this helps.

2021-03-27 20:49 UTC, mahakporwal02 commented
@audiodude I have tried adding intercept as suggested but it still doesn't pass the test.

2021-03-27 20:57 UTC, audiodude commented
@mahakporwal02 Does it pass locally still?

2021-03-27 21:00 UTC, mahakporwal02 commented
> @mahakporwal02 Does it pass locally still?

Yes, it passes locally.

2021-03-27 21:41 UTC, audiodude commented
@mahakporwal02 Okay, so I think I found the problem and fixed it in #309. Can you revert the test to the version without cy.intercept and try again?

2021-03-29 21:51 UTC, audiodude requested changes

2021-03-29 21:51 UTC, audiodude commented on .github/workflows/workflow.yml
> +          curl http://localhost:5000/v1/projects/Alien/table
Could you revert this back to just /v1/projects please?

2021-03-29 21:59 UTC, mahakporwal02 commented
@audiodude Done.

2021-03-29 21:59 UTC, audiodude approved these changes

2021-03-29 22:00 UTC, audiodude commented
Thanks for your dedication to getting this one through. The rest should be easy now. 🤞

2021-03-29 22:00 UTC, merged