added cypress test for article detail table
openzim/wp1 pull request #298
Opened 2021-03-25 19:51 UTC by mahakporwal02

@audiodude Added cypress test for "Clicking a number in the table brings the user to the appropriate article detail list page"
This resolves a part of #286

2021-03-26 17:59 UTC, audiodude requested changes

2021-03-26 17:59 UTC, audiodude commented on wp1-frontend/cypress/integration/home_page.spec.js
> +  it('article detail-list properly displayed', () => {
The string in these it statements should read as a proper sentence. So it would be better as:

`it('displays the article detail-list')`

You also don't need to put  'properly' because we won't normally be testing that something is done improperly.

2021-03-26 17:59 UTC, audiodude commented on wp1-frontend/cypress/integration/home_page.spec.js
> +      cy.get('tr').eq(3).find('td').eq(0).contains(/^\d+$/).click();
This line doesn't use the `text` variable that you invoked. Is there another way of writing this? Can you assign the result of `cy.get('tr').eq(3).find('td').eq(0)` to a variable?

2021-03-26 17:59 UTC, audiodude commented on wp1-frontend/cypress/integration/home_page.spec.js
> +    cy.visit('/#/project/Alien');
If you're visiting a page other than the home page, this should probably go in its own spec. I would call it the `article_page`.

2021-03-30 20:15 UTC, mahakporwal02 commented
@audiodude cypress commands are asynchronous so it may create an issue when I assign `cy.get('tr').eq(3).find('td').eq(0)` to a variable as it might return a promise.

2021-03-30 20:31 UTC, audiodude commented
> @audiodude cypress commands are asynchronous so it may create an issue when I assign `cy.get('tr').eq(3).find('td').eq(0)` to a variable as it might return a promise.

Yup it even tells you that in codefactor: https://www.codefactor.io/repository/github/openzim/wp1/pull/298

2021-03-30 20:33 UTC, mahakporwal02 commented
@audiodude So should just I revert these changes to previous ones?

2021-03-30 20:34 UTC, audiodude commented on wp1-frontend/cypress/integration/home_page.spec.js
> +      cy.get('tr').eq(3).find('td').eq(0).contains(/^\d+$/).click();
Looks like assigning variables is not the way to do things in Cypress 🤷

2021-03-30 20:38 UTC, audiodude commented
> @audiodude So should I just revert these changes to previous ones?

I'm not sure you want to revert all of your changes, but you want to go back to a version that doesn't assign a variable yes.

2021-03-30 20:49 UTC, audiodude approved these changes

2021-03-30 20:49 UTC, merged