cypress test for custom pagination
openzim/wp1 pull request #302
Opened 2021-03-26 13:39 UTC by mahakporwal02

@audiodude Added cypress test for custom pagination.
This resolves a part of #280

2021-03-26 18:06 UTC, audiodude requested changes

2021-03-26 18:06 UTC, audiodude commented on wp1-frontend/cypress/integration/home_page.spec.js
> +    cy.get('tr').eq(0).find('td').eq(0).should('have.text', '51');
What is the difference with `have.text` versus `contain.text` that we use elsewhere. Does have match exactly?

2021-03-26 18:06 UTC, audiodude commented on wp1-frontend/cypress/integration/home_page.spec.js
> +    cy.visit('/#/project/Alien/articles');
You're not visiting the home page, so this doesn't belong in `home_page.spec.js`. Perhaps you can create a file for the article page, `article_page.spec.js`?

2021-03-30 20:19 UTC, mahakporwal02 commented on wp1-frontend/cypress/integration/home_page.spec.js
> +    cy.get('tr').eq(0).find('td').eq(0).should('have.text', '51');
Yes, have.text matches exactly.

2021-04-01 21:07 UTC, audiodude requested changes

2021-04-01 21:07 UTC, audiodude commented on wp1-frontend/cypress/integration/article_page.spec.js
> +describe('custom pagination', () => {
Put this under the `describe('article page')` block, because it's describing the custom pagination on that page. In general, a spec.js file should have one master describe block with other describes nested.

2021-04-01 23:36 UTC, audiodude approved these changes
One nitpick: You shouldn't have to force push the new changes unless you've edited the commits: re-ordered, deleted some, or squashed the. If you haven't done that, please just do a normal push because it will make the code review easier to follow.

2021-04-01 23:36 UTC, merged