Development versions of manual update API server code
openzim/wp1 pull request #316
Opened 2021-03-31 04:08 UTC by audiodude

This PR introduces a `dev_projects` blueprint. If the code is running where ENV = Environment.DEVELOPMENT (as is the case in the example credentials, and is NOT the case in production), the Flask application setup will include dev_projects first, and then the regular projects blueprint.

The effect of this is that endpoints defined in `dev_projects` are used instead of/before the regular ones. This allows us to mock out the manual update process in development, which is what it is immediately used for.

As provided in this PR, the manual update is API compatible with the normal path as far as the frontend is concerned. However it has the following features:

- The "lockout" time between updates is 5 minutes instead of 1 hour.
- All updates take 60 seconds, with the progress being 1/60, 2/60 etc as the seconds pass.
- If the update is for the project 'Water', it will fail after 10 seconds.

Future work would be to make the update duration and wait time configurable. Once that is done, this could be used in CI  to test the manual update page.

2021-03-31 04:12 UTC, audiodude commented
@mahakporwal02 Would you mind doing a code review?

2021-03-31 04:14 UTC, audiodude commented
I'm inclined to submit this without code coverage, because all of the code is just development/test code.

2021-03-31 19:29 UTC, mahakporwal02 commented
@audiodude I'll have a look at it once I make required changes in previous PRs.

2021-04-04 10:31 UTC, mahakporwal02 requested changes
@audiodude Shouldn't we need to update `readme.md` in case the developer needs to test the backend of the manual update.About how to switch blueprint to `projects`?

2021-04-04 10:31 UTC, mahakporwal02 commented on wp1/web/dev/projects.py
> +  clear_project_progress(redis, project_name)
Why to add an extra function? Can't we directly call `clear_project_progress` or are we trying to display the same procedure as the production manual update?

2021-04-04 10:31 UTC, mahakporwal02 commented on wp1/web/dev/projects.py
> +  return progress, 60
In this condition do you mean to show the scenario in #186, where the `progress` is not complete but the `update time` is over?

2021-04-04 10:40 UTC, mahakporwal02 commented on wp1/web/dev/projects.py
> +  return 'started'
Return statement should be of the form `{'status':'started'}`, and for finished case `{'status': 'finished', 'ended_at': ending time}`

2021-04-04 17:47 UTC, mahakporwal02 commented on wp1/web/dev/projects.py
> +    return 'failed'
Also this won't work as progress returned would always be less than or equal to 10 sec.

2021-04-04 17:49 UTC, mahakporwal02 commented on wp1/web/dev/projects.py
> +  dt = datetime.strptime(ts, '%Y-%m-%d %H:%M UTC')
This should also include seconds to get correct value of `secs`.

2021-04-04 18:37 UTC, audiodude commented
> @audiodude Shouldn't we need to update `readme.md` in case the developer needs to test the backend of the manual update.About how to switch blueprint to `projects`?

Good idea. Done.

2021-04-04 18:39 UTC, audiodude commented on wp1/web/dev/projects.py
> +  clear_project_progress(redis, project_name)
Right, the way I developed this was to stub out all of the production functions. It's probably easier to follow this way, if you know how the production functions work. It makes more sense for the API endpoint to call `enqueue_single_project` than to call `clear_project_progress`.

2021-04-04 18:40 UTC, audiodude commented on wp1/web/dev/projects.py
> +  return progress, 60
Yes, I should add that scenario. I should also add the scenario where the update is "in progress" but the progress is greater than the "total".

2021-04-04 18:45 UTC, audiodude commented on wp1/web/dev/projects.py
> +  return 'started'
Good catch, thanks! Done.

2021-04-04 18:46 UTC, audiodude commented on wp1/web/dev/projects.py
> +  dt = datetime.strptime(ts, '%Y-%m-%d %H:%M UTC')
Good point! Done.

2021-04-04 18:47 UTC, audiodude commented on wp1/web/dev/projects.py
> +    return 'failed'
Do you mean because I wasn't producing the seconds on the timestamp? I'm not sure I understand.

2021-04-04 18:51 UTC, audiodude commented on wp1/web/dev/projects.py
> +    return 'failed'
I get it now, just tested it. Fixing.

2021-04-04 19:28 UTC, audiodude commented
@mahakporwal02 Okay I've completed some major changes to this, incorporated your feedback (thanks!) and tried to make it configurable so that it can run in CI. PTAL.

I'm a bit afraid of how complex it's gotten, but I think it's better than not being able to test the manual update page.

2021-04-04 19:34 UTC, mahakporwal02 commented on wp1/web/dev/projects.py
> +  clear_project_progress(redis, project_name)
OK, got it.

2021-04-04 19:36 UTC, audiodude commented on wp1/web/dev/projects.py
> +  return progress, 60
Added those for "Aesthetics" and "Basic Income"

2021-04-04 19:39 UTC, mahakporwal02 commented on wp1/web/dev/projects.py
> +  clear_project_progress(redis, project_name)
OK, got it.

2021-04-04 19:41 UTC, mahakporwal02 commented on wp1/web/dev/projects.py
> +  return progress, 60
> @mahakporwal02 Okay I've completed some major changes to this, incorporated your feedback (thanks!) and tried to make it configurable so that it can run in CI. PTAL.
> 
> I'm a bit afraid of how complex it's gotten, but I think it's better than not being able to test the manual update page.

It has been very helpful to me while I was testing my last PR.

2021-04-04 19:43 UTC, mahakporwal02 commented
@audiodude It has been very helpful while I was testing my last PR. I'll see if I could help you more with these changes.

2021-04-04 19:44 UTC, audiodude commented
> @audiodude It has been very helpful while I was testing my last PR. I'll see if I could help you more with these changes.

Awesome, good to hear. I think if we can get a first version in, even if it's too complex, we can iterate from there.

2021-04-04 19:48 UTC, mahakporwal02 commented
> > @audiodude It has been very helpful while I was testing my last PR. I'll see if I could help you more with these changes.
> 
> Awesome, good to hear. I think if we can get a first version in, even if it's too complex, we can iterate from there.

Seems good.

2021-04-04 19:51 UTC, audiodude commented
Merging with codecov failing, this is development code I don't think it needs to be tested.

The next step is to write some Cypress tests for this page.

2021-04-04 19:51 UTC, merged

2021-04-04 19:53 UTC, mahakporwal02 commented
> Merging with codecov failing, this is development code I don't think it needs to be tested.
> 
> The next step is to write some Cypress tests for this page.

Should I work on cypress tests?

2021-04-04 19:55 UTC, audiodude commented
Yes, feel free to file an issue and write some tests! I'll work on fixing #317