login WIP
openzim/wp1 pull request #345
Opened 2021-05-30 18:46 UTC by mahakporwal02

This work is currently in progress.
I have to still add `/identify` route, error handling, fix css in frontend and some other minor changes.

2021-05-31 01:39 UTC, audiodude requested changes
This is looking really nice and compact, just a few comments.

2021-05-31 01:39 UTC, audiodude commented on wp1-frontend/src/App.vue
> +    localStorage.setItem('token', this.token);
We should not fetch the token from the backend or store it in Local Storage.

2021-05-31 01:39 UTC, audiodude commented on wp1/web/app.py
> +  from wp1.credentials import ENV, CREDENTIALS
Code factor is right that we should have one import for ENV and CREDENTIALS. However, if we don't do the import in get_redis_creds, then in cases where credentials.py doesn't exist, it will be a different error (either a KeyError or a NameError with CREDENTIALS being undefined). Either way, that would cause the server to error out with a cryptic error message.

We want to gracefully handle the case where wp1.credentials doesn't exist.

Perhaps in the except block here you can set ENV = None and CREDENTIALS = None, then check for those values in get_redis_creds() and print an appropriate message if they don't exist.

2021-05-31 01:39 UTC, audiodude commented on wp1/web/app.py
> +  app.config['SECRET_KEY'] = CREDENTIALS[ENV]['SESSION']['secret_key']
Similar to the above, if credentials.py doesn't exist, this will probably blow up with a NameError.

Instead, create a get_session_settings() method that works similarly to get_redis_creds() (and warns the user if credentials.py was undefined).

2021-05-31 01:39 UTC, audiodude commented on wp1/web/oauth.py
> +from wp1.credentials import ENV, CREDENTIALS
Just like in app.py, we need to protect for the case that wp1.credentials doesn't exist, with a try and an `except ImportError`.

2021-05-31 01:39 UTC, audiodude commented on wp1/web/oauth.py
> +consumer_token = ConsumerToken(CREDENTIALS[ENV]['MWOAUTH']['consumer_key'],
If the credentials in fact don't exist, think about what the behavior of this module should be.

2021-05-31 01:39 UTC, audiodude commented on wp1/credentials.py.example
> +        'MWOAUTH': {
Please write a comment about what each of these are.

2021-05-31 01:39 UTC, audiodude commented on wp1/web/oauth.py
> +def token():
This endpoint shouldn't exist

2021-05-31 01:39 UTC, audiodude commented on wp1/web/oauth.py
> +  request_token = request.get_json(force=True)
The user shouldn't need the token to logout. However, you might be worried about CRSF for the logout method, which is a valid concern. In that case, we should integrate a Python CSRF plugin (but you can do that in a follow up PR).

2021-05-31 16:01 UTC, mahakporwal02 commented
@audiodude So the sessions in all three routes happen to be different.
 Please try to run the code.
 You might get what problem acually I am facing

2021-05-31 16:44 UTC, mahakporwal02 commented
@audiodude The problem I am facing is that I am not actually making a request from frontend to backnend, I am redirecting from frontend to backend. So if I redirect how would I get cookies from response?

2021-05-31 18:58 UTC, audiodude requested changes
Make sure to run `pip freeze > requirements.txt` so any new libraries you installed are included.

2021-05-31 19:02 UTC, mahakporwal02 commented
> Make sure to run `pip freeze > requirements.txt` so any new libraries you installed are included.

Done.

2021-05-31 19:51 UTC, audiodude requested changes

2021-05-31 19:51 UTC, audiodude commented on wp1/web/app.py
> +  app.config['SESSION_COOKIE_DOMAIN'] = CREDENTIALS[ENV]['SESSION']['domain']
We should not set SESSION_COOKIE_DOMAIN, because we're always serving the cookies from the same domain they will be sent to. The browser knows "I got a cookie from api.wp1.openzim.org, so I will send it back to that server". And if we put this line, then the cookies don't work in localhost testing.

2021-06-01 21:43 UTC, mahakporwal02 commented on wp1/web/oauth.py
> +consumer_token = ConsumerToken(CREDENTIALS[ENV]['MWOAUTH']['consumer_key'],
@audiodude I have added error handling but what should be done when credentials.py doesnot exist?
Should we take input from user?

2021-06-01 22:12 UTC, mahakporwal02 commented
@audiodude Sorry I forgot and force-pushed.
Will remeber it from next time.

2021-06-02 00:49 UTC, audiodude requested changes
Looking good, just a few things to clean up. Please remember not to force push next time, thanks!

2021-06-02 00:49 UTC, audiodude commented on wp1-frontend/src/App.vue
> +      await fetch(`${process.env.VUE_APP_API_URL}/oauth/logout`);
I think you need credentials: include here too, because otherwise how will the backend know which session to logout?

2021-06-02 00:49 UTC, audiodude commented on wp1-frontend/src/App.vue
> +          if (response.status === 200) {
https://developer.mozilla.org/en-US/docs/Web/API/Response/ok

2021-06-02 00:49 UTC, audiodude commented on wp1-frontend/src/App.vue
> +      const response = await fetch(
I would call this `const data =` because you're returning the data, not the response object.

2021-06-02 00:49 UTC, audiodude commented on wp1-frontend/src/App.vue
> +        .then(data => {
This is superfluous. It takes data and just returns it.

2021-06-02 00:49 UTC, audiodude commented on wp1/credentials.py.example
> +        # secret key for session
Please explain how this should be populated in production, eg tips on how to generate a good secret key.

2021-06-02 00:49 UTC, audiodude commented on wp1-frontend/src/App.vue
> +            <span> {{ this.username }} </span>
nit: put a "&nbsp;|&nbsp;" between the button and the span.

2021-06-02 00:49 UTC, audiodude commented on wp1/web/app.py
> +  app.config.from_object(__name__)
What does this do? I was under the impression that it's a convenience method for setting config variables based on "floating" variables in the module namespace. Why do we need it here?

2021-06-02 00:49 UTC, audiodude commented on wp1/web/oauth.py
> +      'No credentials.py file found, Please add your mwoauth credentials in credentials.py'
nit: line length.

2021-06-02 00:49 UTC, audiodude commented on wp1/web/oauth.py
> +    username = handshaker.identify(session['access_token'])['username']
Instead of doing a network request here (and every time a page is loaded), why don't we store the username in the session?

Then identify() looks like this:

```
def identify():
  username = session.get('username')
  if username is None:
     flask.abort(401, 'Unauthorized')
     return
  return jsonify(username)
```

2021-06-02 00:49 UTC, audiodude commented on wp1/web/oauth.py
> +    session.pop('access_token')
If you're going to use my suggestion about storing the username in the session, then you probably want to have a single key in the session for the access_token and username so that you can pop just one thing here. Maybe:

```
  session['user'] = {'access_token': access_token, 'username': username}
```

2021-06-02 00:49 UTC, audiodude commented on wp1/web/oauth.py
> +  try:
In general, you should wrap a try/except around the smallest possible snippet of code. Here, I think you're expecting the KeyError from line 32, so really that's all that should be in the try/except.

In honesty, you should really be doing:

```
if 'request_token' not in session:
  flask.abort(404, 'User does not exist')
....rest of method....
```

2021-06-02 00:49 UTC, audiodude commented on wp1/web/oauth.py
> +    return {'status:': '200'}
Use `204 NO CONTENT` for responses that are successful but have no body.

2021-06-02 00:49 UTC, audiodude commented on wp1/web/oauth.py
> +  redirect, request_token = handshaker.initiate()
What if the user is already logged in? Should we really send them back to Wikipedia?

2021-06-02 00:49 UTC, audiodude commented on wp1/web/oauth.py
> +import flask
Overall, the pattern of:

```
try:
  do 
  a whole
  bunch
  of things
except OneSpecificError:
  flask.abort(404)
```

Is an anti-pattern. As I mention in other comments, try/except blocks should be limited in scope to the exact lines that can throw the exception. Additionally, there is no need to pop from a dictionary like object if you know the key might not be in it, then wait for an exception to occur. Instead, just use tests like `in` or access like `.get(key_name)`. If those "fail" then you can send your error statuses.

2021-06-02 00:49 UTC, audiodude commented on wp1/web/oauth.py
> +    return jsonify(username)
We might someday need to return other information about the user. Instead of returning a "naked" string here, try using a simple dictionary, like:

```
jsonify({'username': username})
```

That way, if the user data changes, the code that retrieves the username from the backend won't have to. (You'll also need to update the Vue app of course.)

2021-06-02 00:52 UTC, audiodude commented
Please also make sure tests are passing, and I think you need to write some tests for your OAuth endpoints.

2021-06-02 15:24 UTC, mahakporwal02 commented on wp1/credentials.py.example
> +        # secret key for session
Should I add these comments
```
To get your random secret key for production use the following script
python3
import os
os. urandom(24)
```

2021-06-02 22:17 UTC, mahakporwal02 commented on wp1-frontend/src/App.vue
> +            <span> {{ this.username }} </span>
@audiodude Can I do all the UI changes in seperate PR?

2021-06-02 22:41 UTC, mahakporwal02 commented
> Please also make sure tests are passing, and I think you need to write some tests for your OAuth endpoints.

@audiodude I will make two separate commits 
first one involving ui changes and adding authorisation on manual update second involving tests for the new endpoints.
The tests are failing in the main branch, we need to fix that as well.

2021-06-03 01:35 UTC, audiodude commented on wp1/credentials.py.example
> +        # secret key for session
That would work.

2021-06-03 01:40 UTC, audiodude commented
> > Please also make sure tests are passing, and I think you need to write some tests for your OAuth endpoints.
> 
> @audiodude I will make two separate commits
> first one involving ui changes and adding authorisation on manual update second involving tests for the new endpoints.

I agree that requiring login for manual update should be its own PR. However the general rule should be to add tests for code in the same PR that adds the code.

> The tests are failing in the main branch, we need to fix that as well.
I checked, and I believe the tests are passing on main: https://github.com/openzim/wp1/actions/runs/886353197

That's the last CI that ran on main, when I merged my dev-db branch.

2021-06-03 01:41 UTC, audiodude commented
It looks like your test errors are related to the ENV variable not being defined in certain places: https://github.com/openzim/wp1/pull/345/checks?check_run_id=2732274725#step:8:724

2021-06-05 20:53 UTC, audiodude requested changes
The tests look good, but you need to handle the case where CREDENTIALS are missing. I think there are some db tests that do this by mocking the CREDENTIALS variable in the module under test.

2021-06-05 20:53 UTC, audiodude commented on wp1/web/oauth_test.py
> +  # The credentials module isn't checked in and may be missing
Actually, in unit tests the credentials module is _always_ missing. You should design your tests so that they work without them, or in some cases with the module mocked out.

2021-06-05 20:53 UTC, audiodude commented on wp1/web/oauth_test.py
> +      self.assertEqual('401 UNAUTHORIZED', rv.status)
These should be two separate tests:

1. When there is nothing in the session, it returns 401
2. When the session has a 'user' key it returns the correct username.

2021-06-05 20:53 UTC, audiodude commented on wp1-frontend/src/App.vue
> +            <span> {{ this.username }} </span>
What other UI changes are there?

2021-06-05 20:53 UTC, audiodude commented on wp1/credentials.py.example
> +        # import os
I think you're missing a step here.

2021-06-05 20:53 UTC, audiodude commented on wp1/web/app.py
> +  print('''No credentials.py file found, Development overlay
nit: Instead of a triple quoted string, use implicit string joining to avoid line length limits. Like this:

```
print('No credentials.py file found. Development overlay will '
         'not be enabled.')
```

2021-06-05 20:53 UTC, audiodude commented on wp1/web/app.py
> +  if CREDENTIALS is None or CREDENTIALS[ENV].get(
```
missing_credentials = CREDENTIALS is None or ENV is None
if not missing_credentials:
  mwoauth = CREDENTIALS.get(ENV, {}).get(MWOAUTH, {})
if missing_credentials or mwoauth.get('consumer_key') is None or mwoauth.get('consumer_secret') is None:
  ....
```

2021-06-05 20:53 UTC, audiodude commented on wp1/web/oauth_test.py
> +@unittest.skipIf(skip, 'Cannot find Credentials.py')
Like mentioned previously, this is incorrect because credentials.py will never be checked in for unit tests.

2021-06-05 21:32 UTC, mahakporwal02 commented on wp1/credentials.py.example
> +        # import os
Regarding UI changes, do you want me to change anything else?

2021-06-05 21:52 UTC, mahakporwal02 commented
> What other UI changes are there?
Do you have any changes in mind?

2021-06-07 21:23 UTC, audiodude requested changes
You've definitely got the idea now, good work. I think you still need additional test code though, because I see a lot of Codecov warnings that lines are not tested.

2021-06-07 21:23 UTC, audiodude commented on wp1/base_db_test.py
> +          'API': {},
This is the right idea, but the oauth creds don't really belong in the base_db_test file.

2021-06-07 21:23 UTC, audiodude commented on wp1/web/oauth_test.py
> +  @patch('wp1.web.app.CREDENTIALS', get_test_connect_creds())
Instead, just put the oauth credentials in a constant object (TEST_OAUTH_CREDS) and use that constant instead of get_test_connect_creds().

2021-06-07 21:42 UTC, mahakporwal02 commented
> You've definitely got the idea now, good work. I think you still need additional test code though, because I see a lot of Codecov warnings that lines are not tested.

I have to mock out the oauth parts and I think Codecov warnings are related to that?

2021-06-07 21:43 UTC, audiodude commented
> there

There will be changes but none that are applicable to this PR

2021-06-07 21:44 UTC, audiodude commented
> > What other UI changes are there?
> 
> Do you have any changes in mind?

There will be other changes of course, but none that I can think of as part of this PR

2021-06-07 21:45 UTC, audiodude commented
> > You've definitely got the idea now, good work. I think you still need additional test code though, because I see a lot of Codecov warnings that lines are not tested.
> 
> I have to mock out the oauth parts and I think Codecov warnings are related to that?

Right, the codecov warnings are telling you which parts of the code are untested. I'm glad you have plans to test those parts.

2021-06-07 21:45 UTC, mahakporwal02 commented
So should I just change code for the above two comments (regarding the test_ oauth_creds object) for this PR?

2021-06-07 21:46 UTC, audiodude commented
> So should I just change code for the above two comments (regarding the test_ oauth_creds object) for this PR?

Yes. If I make a comment with 'requested changes' as the review, it means you should make those changes

2021-06-08 21:30 UTC, audiodude commented on wp1/web/oauth.py
> +try:
Do you still need this try/except block? If the credentials are missing, won't this module never get imported?

2021-06-09 20:55 UTC, mahakporwal02 commented on wp1/web/oauth.py
> +try:
Yes we will need that. 
In case of tests (mock) it will give error in import.

2021-06-09 21:11 UTC, audiodude requested changes
Just one nit on the triple quoted string, but otherwise the new tests look really good!

2021-06-09 21:11 UTC, audiodude commented on wp1/web/oauth.py
> +  print('''No credentials.py file found,
I believe we talked about this before, but prefer implicit string concatenation over triple quoted strings, for line length purposes:

```
print('No credentials.py file found, Please add your '
         'mwoauth credentials in credentials.py')

2021-06-09 21:17 UTC, mahakporwal02 commented on wp1/web/oauth.py
> +  print('''No credentials.py file found,
Should I squash the commits?

2021-06-09 21:22 UTC, audiodude commented on wp1/web/oauth.py
> +  print('''No credentials.py file found,
No, I don't think so. I personally believe that squashing is time consuming and error prone. We can merge just like this.

2021-06-10 16:54 UTC, audiodude approved these changes
LGTM

2021-06-11 01:46 UTC, merged