added authorisation on manual updates
openzim/wp1 pull request #353
Opened 2021-06-12 12:45 UTC by mahakporwal02

@audiodude This fixes #350

2021-06-12 18:01 UTC, audiodude requested changes
Great work on the backend, but I think the frontend needs some changes. We should not hide the manual update feature from non logged in users, and I'm not sure we need Vuex.

2021-06-12 18:01 UTC, audiodude commented on wp1/web/__init__.py
> +def authenticate(f):
This is a great helper decorator.

2021-06-12 18:07 UTC, audiodude commented on wp1-frontend/src/components/UpdatePage.vue
> +  <div v-if="isLoggedIn">
Additionally, we need a mechanism so that once you log in you are redirected back to the manual update page. Some kind of `&next=/#/update` parameter that gets stored in the session.

2021-06-13 19:15 UTC, audiodude requested changes
A few styling changes: we really want to take advantage of Bootstrap and not have custom styles. Also I think you need a few more tests, but besides that this looks really good!

2021-06-13 19:15 UTC, audiodude commented on wp1-frontend/src/components/UpdatePage.vue
> +    <h2 class="content-style" style="padding-top: 250px">
Instead of an explicit padding, use the bootstrap "p-1" "p-2" etc classes. Here and below.

2021-06-13 19:15 UTC, audiodude commented on wp1-frontend/src/components/UpdatePage.vue
> +      loginInitiateUrl: `${process.env.VUE_APP_API_URL}/oauth/initiate?next=update`
Let's go with just `loginUrl`.

2021-06-13 19:15 UTC, audiodude commented on wp1-frontend/src/components/UpdatePage.vue
> +  display: flex;
You shouldn't have to manually `display: flex` anything, you should be able to use Bootstrap rows and columns to get the desired effect.

2021-06-13 19:15 UTC, audiodude commented on wp1/web/oauth.py
> +  if session.get('next_path'):
You should use `session.pop` here, because we want to consume the next path value and not have it "hang around" potentially for the next login.

2021-06-13 19:15 UTC, audiodude commented on wp1/web/oauth_test.py
> +        sess['next_path'] = '/'
There should be a new test for when the user requests initiate and has a `next=` param. There should also be a test for when the user hits `complete` and there is a `next_path` in the session.

2021-06-14 17:35 UTC, audiodude requested changes
Looking good, just a few small issues.

2021-06-14 17:35 UTC, audiodude commented on wp1-frontend/src/components/UpdatePage.vue
> +      style="padding-top: 10px;"
Same thing here, use pt-* instead

2021-06-14 17:35 UTC, audiodude commented on wp1/web/oauth.py
> +  session.pop('next_path')
Doesn't pop return the value? So shouldn't you just be able to do `next_path = session.pop('next_path')`?

2021-06-14 17:41 UTC, audiodude commented on wp1-frontend/src/components/UpdatePage.vue
> +      ><button>Login</button></a
Also, make sure to use the Bootstrap button classes: `type="button"` and `class="btn btn-primary"`.

https://getbootstrap.com/docs/4.0/components/buttons/

2021-06-14 19:16 UTC, mahakporwal02 commented on wp1-frontend/src/components/UpdatePage.vue
> +      ><button>Login</button></a
should I add these classes to other login button also?

2021-06-14 19:24 UTC, audiodude commented on wp1-frontend/src/components/UpdatePage.vue
> +      ><button>Login</button></a
Yes, the login button should have `btn-primary` but the logout button should be `btn-secondary`.

2021-06-14 20:11 UTC, mahakporwal02 commented
> Remove print statement

Sorry for that

2021-06-14 20:17 UTC, audiodude approved these changes
LGTM

2021-06-14 20:17 UTC, merged