added basic route for sites
openzim/wp1 pull request #368
Opened 2021-06-21 22:08 UTC by mahakporwal02

This fixes #366 
I will create a separate commit for documentation and testing.

2021-06-21 22:16 UTC, audiodude commented
Actually you should do the documentation and tests in the same PR. For codecov at least it will mark the PR as red if there are no tests.

2021-06-21 22:32 UTC, mahakporwal02 commented
> Actually you should do the documentation and tests in the same PR. For codecov at least it will mark the PR as red if there are no tests.

Yes, I was talking about different commit not a new PR.

2021-06-21 23:00 UTC, audiodude requested changes
You definitely have the basic flow down here, just a few nits about code style.

2021-06-21 23:00 UTC, audiodude commented on wp1/web/sites.py
> +  if redis.get('sites'):
```suggestion
  sites = redis.get('sites')
  if sites is not None:
```

2021-06-21 23:00 UTC, audiodude commented on wp1/web/sites.py
> +    return {'data': redis.get('sites').decode('utf-8').split(',')}
```suggestion
    return {'sites': sites.decode('utf-8').split(',')}
```

2021-06-21 23:00 UTC, audiodude commented on wp1/web/sites.py
> +  result['sitematrix'].pop('specials')
```suggestion
  sitematrix = result['sitematrix']
  sitematrix.pop('specials')
```

Since you use result['sitematrix'] so many times.

2021-06-21 23:00 UTC, audiodude commented on wp1/web/sites.py
> +  response = []
```suggestion
  sites = []
```

It's good to use the same variable name here as in the caching code above, so that readers can understand we're referring to the same data.

2021-06-22 03:11 UTC, audiodude commented on wp1/web/sites.py
> +  if redis.get('sites'):
Actually I see now that sites is the name of the blueprint. So maybe `sites_data`, here and elsewhere.

2021-06-22 03:12 UTC, audiodude commented on wp1/web/sites.py
> +_ua = 'WP1.0Bot/3.0. Run by User:Audiodude. Using mwclient/0.9.1'
Rename this variable from _ua to MW_USER_AGENT and then import it for use here:

https://github.com/openzim/wp1/blob/main/wp1/api.py#L9

2021-06-22 22:38 UTC, audiodude requested changes
Looks good, just some naming and other nits.

2021-06-22 22:38 UTC, audiodude commented on wp1/web/sites.py
> +    return {'sites_data': sites_data.decode('utf-8').split(',')}
```suggestion
    return {'sites': sites_data.decode('utf-8').split(',')}
```

2021-06-22 22:38 UTC, audiodude commented on wp1/web/sites.py
> +  sitematrix = result['sitematrix']
```suggestion
  sitematrix = site.api('sitematrix')['sitematrix']
```

2021-06-22 22:38 UTC, audiodude commented on wp1/web/sites.py
> +  redis.setex('sites', timedelta(days=1), value=','.join(sites_data))
```suggestion
  redis.setex('sites_data', timedelta(days=1), value=','.join(sites_data))
```

2021-06-22 22:38 UTC, audiodude commented on wp1/web/sites.py
> +  return {'sites_data': sites_data}
```suggestion
  return {'sites': sites_data}
```

2021-06-22 22:38 UTC, audiodude commented on wp1/web/sites_test.py
> +      "sitematrix": {
Please use single quotes.

2021-06-22 22:38 UTC, audiodude commented on wp1/web/sites_test.py
> +  sites = ["https://aa.wikipedia.org", "https://ab.wikipedia.org"]
Single quotes

2021-06-22 22:38 UTC, audiodude commented on wp1/web/sites_test.py
> +  @patch('wp1.web.sites.mwclient.Site')
Why do you need to patch this?

2021-06-22 22:38 UTC, audiodude commented on wp1/web/sites_test.py
> +  def test_get_cached_sites(self):
You should patch `wp1.web.sites.site` here and assert that it wasn't called as well.

2021-06-22 22:38 UTC, audiodude commented on openapi.yml
> +                  sites_data:
```suggestion
                  sites:
```

2021-06-23 18:29 UTC, audiodude commented on wp1/web/sites_test.py
>            "count":
Please prefer single quotes on all lines, here and everywhere.

2021-06-23 18:30 UTC, audiodude commented on wp1/web/sites_test.py
> +      'sitematrix': {
Please prefer single quotes for all elements of this dictionary and in all cases. Thanks.

2021-06-23 18:31 UTC, audiodude commented on wp1/web/sites_test.py
> +  @patch('wp1.web.sites.mwclient.Site')
?

2021-06-23 18:36 UTC, mahakporwal02 commented on wp1/web/sites_test.py
> +  @patch('wp1.web.sites.mwclient.Site')
Without patching `wp1.web.sites.mwclient.Site` , `wp1.web.sites.site` is not getting patched

2021-06-23 18:36 UTC, mahakporwal02 commented on wp1/web/sites_test.py
> +  @patch('wp1.web.sites.mwclient.Site')
Already tried patching it

2021-06-23 18:38 UTC, audiodude commented on wp1/web/sites_test.py
> +  @patch('wp1.web.sites.mwclient.Site')
Can you explain why that is the case? We should avoid having "magic code".

2021-06-23 18:43 UTC, audiodude commented on wp1/web/sites_test.py
> +  @patch('wp1.web.sites.mwclient.Site')
Nevermind I see the problem. Because `@patch` is a decorator, the parameters get sent to the patched function in reverse order than they appear in the decorator list. So in your case `patched_site` is actually this line, line 63, the patched mwclient. The first patch statement contributes the second function argument and is actually the one that is unused. Please remove it.

2021-06-23 19:00 UTC, audiodude requested changes
Just the test changes and we're good!

2021-06-23 20:05 UTC, audiodude approved these changes
LGTM

2021-06-23 20:06 UTC, merged