added UI for creating list
openzim/wp1 pull request #369
Opened 2021-06-24 14:05 UTC by mahakporwal02

This fixes #367 
Shouldn't this be under the `Create Simple List` page (currently in mock-up it was under My Lists)?

2021-06-24 15:00 UTC, audiodude requested changes
Yes, it should be under CreateSimpleList, that was a bug in the mockup.

Perhaps this wasn't clear, but you should include the following:

1. The logic for fetching the sitematrix that you added in the previous PR and populating the `<select>` element. The initial list on page load can just be a hardcoded `['en.wikipedia.org']`
2. Validation logic for the form, as described in the mock issue.
3. Cypress tests.

Thanks!

2021-06-24 16:50 UTC, mahakporwal02 commented
> Yes, it should be under CreateSimpleList, that was a bug in the mockup.
> 
> Perhaps this wasn't clear, but you should include the following:
> 
> 1. The logic for fetching the sitematrix that you added in the previous PR and populating the `<select>` element. The initial list on page load can just be a hardcoded `['en.wikipedia.org']`
> 2. Validation logic for the form, as described in the mock issue.
> 3. Cypress tests.
> 
> Thanks!

Sorry I didn't see you have already reviewed the PR thats why I force pushed.

2021-06-24 16:54 UTC, audiodude commented
> Sorry I didn't see you have already reviewed the PR thats why I force pushed.

Actually you should definitely force push, once you've transferred the changes to CreateSimpleList.vue. We don't need a commit that makes the changes to MyLists.vue.

2021-06-24 16:56 UTC, mahakporwal02 commented
> > Sorry I didn't see you have already reviewed the PR thats why I force pushed.
> 
> Actually you should definitely force push, once you've transferred the changes to CreateSimpleList.vue. We don't need a commit that makes the changes to MyLists.vue.

Also, can you please elaborate what should be done in validation logic?

2021-06-24 17:00 UTC, audiodude commented
> Also, can you please elaborate what should be done in validation logic?
> Should I just add checks for spaces?

The rigorous validation of the list will be handled by the backend, because it will potentially involve checking that the articles actually exist in the specified project. Otherwise, the validation is as described in #367: The name cannot be empty and the list cannot be empty.

2021-06-24 18:28 UTC, kelson42 commented
The article existence check on the backend is an expensive operation to run and not totally trivial to implement efficiently. I don't know if its implementation is part of this ticket, but I would differentiate it from a pure syntaxic check and recommend to open a dedicated ticket for it.

2021-06-24 19:57 UTC, audiodude requested changes
I'm going to download this PR and run it locally to make sure everything looks good. Otherwise, I think your tests need improvement, but the page itself looks pretty good.

2021-06-24 19:57 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +    cy.get('nav').contains('Create Simple List');
This will be true of several pages besides Create Simple List

2021-06-24 19:57 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +    cy.get('select').select('ab.wikipedia.org');
We need to mock out the request for this, because we don't want to call the actual Mediawiki API in CI.

2021-06-24 19:57 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +  it('displays List Name', () => {
I think what you actually want is the opposite of this: that when you don't have a list name, you get an error. Also in general, a test that doesn't make any assertions about the state of the page is not a good test.

2021-06-24 19:57 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +  it('displays textbox', () => {
Same thing, this doesn't test anything.

2021-06-24 19:57 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
> +                  {{ item.replace('https://', '') }}
You should perform this transformation in the data fetching function so that the select can simply display the items. Also, if you're going to hardcode en.wikipedia.org, you should remove it from the list so it doesn't appear twice.

2021-06-24 19:57 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
> +                placeholder="Article names with either 'Spaces between words' or 'Underscores_between_words'"
Change this placeholder to be an appropriate list of items of some sort:

```
placeholder="Eiffel_Tower
Statue_of_Liberty
Freedom_Monument_(Baghdad)
George-Étienne_Cartier_Monument"
```

Note that this list contains both parenthesis and non-ASCII characters

2021-06-24 19:57 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
> +      wikiProjects: ['en.wikipedia.org']
If you've encoded this here, you don't need to hardcode it in the <select> construction.

2021-06-24 21:16 UTC, mahakporwal02 commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +  it('displays textbox', () => {
So should I remove this for now?

2021-06-24 21:17 UTC, mahakporwal02 commented on wp1-frontend/src/components/CreateSimpleList.vue
> +      wikiProjects: ['en.wikipedia.org']
I am removing it from the list.
I have to hardcode here because it should be seen as default option in select.

2021-06-25 16:36 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
> +      wikiProjects: ['en.wikipedia.org']
This array can be empty, because your HTML contains a literal `<option>` for en.wikipedia.org. That will render no matter what is in the list.

2021-06-25 16:49 UTC, audiodude requested changes
Using HTML5 validation works, but we want custom validation with Bootstrap style colors and messages displayed inline. Please implement this and update the tests. Thanks!

2021-06-25 16:49 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +    cy.intercept('v1/sites/', { fixture: 'sites.json' });
You need to do this in a `beforeEach` in this describe block. Otherwise, you're not doing it for every test.

2021-06-25 16:49 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +  it('displays list name', () => {
The name of this test should be updated, because it's now testing that the validation works.

2021-06-25 16:49 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +    cy.get('#listName')
Why do you need to type into the text input?

2021-06-25 16:49 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
> +                required="true"
Although this technically prevents the user from submitting an empty list name, the UI with alerts is not particularly user-friendly. What we would like is a validation function on this page that runs on the `<input>` onBlur, as well as when the save button is clicked. It should change the style of the inputs and display inline error messages, similar to: https://getbootstrap.com/docs/5.0/forms/validation/#custom-styles

Apologies that this wasn't in the mock.

2021-06-25 16:49 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
> +        }
I know in Python you get bugs if you modify a list while you're iterating over it. The same is probably true in Javascript? Why not just:

```suggestion
      index = this.wikiProjects.indexOf('https://en.wikipedia.org')
      this.wikiprojects.splice(index, 1);
```

2021-06-26 17:16 UTC, audiodude requested changes
Just a couple of nits, but this looks really close!

2021-06-26 17:16 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
> +      wikiProjects: ['en.wikipedia.org']
If you have this list populated on page load, as well as the hardcoded literal `<option>` you get the following:

<img width="783" alt="Screen Shot 2021-06-26 at 10 12 06 AM" src="https://user-images.githubusercontent.com/57832/123520764-28d5ae00-d667-11eb-87e8-75569693abb7.png">

The array should be empty.

2021-06-26 17:16 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
> +  border: 1px solid #000;
I don't think this is necessary, let's just use the default Bootstrap styles.

2021-06-26 17:17 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
> +        <div class="m-4" style="font-weight: 550;">
This doesn't need to be bold, remove `font-weight` (and generally avoid inline styles).

2021-06-26 17:54 UTC, mahakporwal02 commented
@audiodude 
Regarding "Still wondering this."
I have asserted that the div with id="listName" contains this text when field is empty.

2021-06-26 18:01 UTC, audiodude commented
> @audiodude
> Regarding "Still wondering this."
> I have asserted that the div with id=`listName` contains the text `Please provide a valid List Name.` when field is empty.

But there are no assertions after the typing.

2021-06-26 18:04 UTC, mahakporwal02 commented
> > @audiodude
> > Regarding "Still wondering this."
> > I have asserted that the div with id=`listName` contains the text `Please provide a valid List Name.` when field is empty.
> 
> But there are no assertions after the typing.
I am a bit confused
So should I add 
`cy.get('#listName').should('contain.text', 'Please provide a valid List Name.')`; instead of
`cy.get('#listName').contains('Please provide a valid List Name.')`;

2021-06-26 18:07 UTC, mahakporwal02 commented
> > @audiodude
> > Regarding "Still wondering this."
> > I have asserted that the div with id=`listName` contains the text `Please provide a valid List Name.` when field is empty.
> 
> But there are no assertions after the typing.

OK, I get it

2021-06-26 18:07 UTC, audiodude commented
> > > @audiodude
> > > Regarding "Still wondering this."
> > > I have asserted that the div with id=`listName` contains the text `Please provide a valid List Name.` when field is empty.
> > 
> > 
> > But there are no assertions after the typing.
> 
> I am a bit confused
> So should I add
> `cy.get('#listName').should('contain.text', 'Please provide a valid List Name.')`; instead of
> `cy.get('#listName').contains('Please provide a valid List Name.')`;

The test has three lines:

```
    cy.get('#saveListButton').click();
    cy.get('#listName').contains('Please provide a valid List Name.');
    cy.get('#listName')
      .click()
      .type('My List');
```

On the first line you click the save button. On the second line you make an assertion. Then, on the third line, you type 'My List' into the name box. But that's the final line, there are no assertions after that. So what I'm wondering is: what is the point of typing into the `#listName` box?

2021-06-26 18:08 UTC, audiodude commented
> > > @audiodude
> > > Regarding "Still wondering this."
> > > I have asserted that the div with id=`listName` contains the text `Please provide a valid List Name.` when field is empty.
> > 
> > 
> > But there are no assertions after the typing.
> 
> OK, I get it

Awesome! Also in the future, please try to keep discussion about specific code review items in the relevant conversation and off the main thread of the PR. Thanks!

2021-06-26 19:48 UTC, audiodude approved these changes
LGTM

2021-06-26 19:49 UTC, merged