Create backend endpoint for saving simple lists
openzim/wp1 pull request #381
Opened 2021-06-30 18:17 UTC by mahakporwal02

This fixes #379

2021-06-30 18:22 UTC, mahakporwal02 commented
@audiodude Sorry for the late PR.

2021-07-01 01:43 UTC, audiodude commented
> @audiodude Sorry for the late PR.

I don't consider this late by any means, thanks!

2021-07-01 02:02 UTC, audiodude requested changes
I think perhaps I didn't specify this clearly enough. The backend endpoint should eventually be the one we are going to use to save simple lists. As such, the URL should be `/selection/simple/`. The endpoint should not be called on validation, but on save, for this reason.

Also, since it is being called on save, it should return 200 for all valid requests. The 403 status generally means "NOT AUTHORIZED" and should be reserved for if the user attempts to save a list but is not logged in.

In the openapi.yml specification, you should describe in detail the meanings of the success boolean and what happens for values of true and false respectively. The response should not contain a redundant "status" field.

Also, the frontend should clear/hide the invalid items when submitting a second time. The idea is that I should be able to have a list of items, see which ones are invalid, and then click "Save" again and the list should save.

Sorry for any miscommunication!

2021-07-01 02:03 UTC, audiodude commented
Additionally, even though the frontend validates that the name and project are not empty, you should check these again on the API backend for "defense in depth" and the possibility that a request is being made from outside of our frontend.

2021-07-01 16:22 UTC, audiodude requested changes
It looks like you need to clean up the front end code a bit, but otherwise this is moving in the right direction.

2021-07-01 16:22 UTC, audiodude commented on openapi.yml
> +                    default: false
Remove. I don't think this is a valid use of the `default` indicator.

2021-07-01 16:22 UTC, audiodude commented on openapi.yml
> +                article_name:
Just call this `articles`.

2021-07-01 16:22 UTC, audiodude commented on openapi.yml
> +                project_name:
Just call this `project`.

2021-07-01 16:22 UTC, audiodude commented on openapi.yml
> +                    type: boolean
Can't you put a description or other annotation here to describe when it would be true or false? Same with other responses.

2021-07-01 16:22 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
>    name: 'MyLists',
Why is the name still 'MyLists'? Didn't we fix that in the previous PR?

2021-07-01 16:22 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
> +            <select ref="select" class="custom-select my-list">
How about `ref="project"`?

2021-07-01 16:22 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
> +              ref="article_name"
How about `ref="articles"`?

2021-07-01 16:22 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
> +    saveForm: function() {
nit: Just call this `save`, we know there's a form involved.

2021-07-01 16:22 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
> +      form.addEventListener(
You don't need to add an event listener manually. Look at the example on https://vuejs.org/v2/guide/events.html

`<form v-on:submit.prevent="onSubmit"></form>`

2021-07-01 16:22 UTC, audiodude commented on wp1/web/selection.py
> +def get_article_names():
`def create`

2021-07-01 16:22 UTC, audiodude commented on wp1/web/selection.py
> +  list_name = flask.request.get_json()['list_name']
Don't call .get_json() twice. Call it once and store the result in an intermediate variable.

2021-07-01 16:22 UTC, audiodude commented on wp1/web/selection_test.py
> +  def test_get_unsuccessful_article_name(self):
`def test_create_unsuccessful`

2021-07-01 16:22 UTC, audiodude commented on wp1/web/selection_test.py
> +  def test_get_successful_article_name(self):
`def test_create_successful`

2021-07-01 16:22 UTC, audiodude commented on wp1/web/selection_test.py
> +class ProjectTest(unittest.TestCase):
You're missing tests for the 400 when the articles, list name, or project are missing. Should be three separate tests.

2021-07-01 18:42 UTC, mahakporwal02 commented on wp1-frontend/src/components/CreateSimpleList.vue
>    name: 'MyLists',
We had changed the name from 'createSimpleLists' to 'MyLists'. Should I change it again?

2021-07-01 18:44 UTC, mahakporwal02 commented on openapi.yml
> +                    default: false
If I remove `default` the boolean value sets itself to `true`.But the `success` should be `false` if we are returning items

2021-07-02 22:11 UTC, audiodude commented on openapi.yml
> +                    default: false
You should remove it. I don't know what you mean by "sets itself to true".

2021-07-02 22:28 UTC, audiodude requested changes
Thanks for sticking with this one! Although it is mostly correct as is, I think we can make some changes to really add polish. Thanks!

2021-07-02 22:28 UTC, audiodude commented on openapi.yml
> +                    description: True when article name doesnot contain forbidden chars {"#", "<", ">", "[", "]", "{", "}", "|"}, false otherwise.
nit: s/doesnot/does not/

2021-07-02 22:28 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
> +        <form v-on:submit.prevent class="needs-validation" novalidate>
Shouldn't the value of this attribute be your save method? You want to call the save method on submit right?

2021-07-02 22:28 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
> +      const form = document.querySelectorAll('.needs-validation')[0];
Why not give the form a ref attribute so you can get it directly?

2021-07-02 22:28 UTC, audiodude commented on wp1/web/selection.py
> +  valid_article_names, invalid_article_names, forbiden_chars = selections.validate_list(
nit: line too long?

2021-07-02 22:28 UTC, audiodude commented on wp1/web/selection.py
> +        "status": "200",
You shouldn't return a "status" field, that's redundant with the HTTP status.

2021-07-02 22:28 UTC, audiodude commented on wp1/web/selection.py
> +  list_name = response['list_name']
You need to edit these parameter names to match what's in the openapi.yml. Then you'll need to update the tests as well.

2021-07-02 22:28 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +        e.preventDefault();
This shouldn't be necessary anymore.

2021-07-02 22:28 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +      'Following items are not valid for selection lists beacuse they have #'
s/beacuse/because/

You'll have to fix it in the actual form as well, too.

2021-07-02 22:28 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +  it('unsucessful response', () => {
The it clause should read like a sentence, and capture the behavior you're trying to test. So "It unsuccessful response" is not a logical sentence. Something like "It flams the whoobong when the blah blah blah" -> `it('flams the whoobong when the blah blah blah')`.

It looks like I didn't catch this for the initial tests on this page, but you should go back and edit those it blocks as well. It would be fine to do that in this same PR.

2021-07-02 22:28 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +  it('successful response', () => {
Same as above with regard to it calls reading like a sentence.

2021-07-02 22:28 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +      .type('Eiffel_Tower\nStatue of Liberty#');
You should make it more obvious which item is invalid. Even something like `.../nInvalid#Item` would be better

2021-07-02 22:28 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +      'Statue_of_Liberty#'
Do you think it's a bug that the user typed 'Statue of Liberty#' and we told them that 'Statue_of_Liberty#' (with underscores) is invalid? Maybe we can do better. Just something to think about maybe for a follow up PR.

2021-07-02 22:28 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
>          this.wikiProjects[index] = element.replace('https://', '');
Do you think we should maybe do this in the selection list retrieval code (where we get the URLs from the meta wikipedia API)? Do we have any use for full URLs with https?

2021-07-02 22:28 UTC, audiodude commented on openapi.yml
> +      summary: 'Get response from sending acticle names'
"Get response" is not the best documentation. All HTTP endpoints return a response. Think about what the user is actually doing when they call this endpoint. Something like 'Save a new Simple list, validating it first and returning invalid items if they exist'. Okay I guess I wrote it for you ;)

2021-07-02 22:28 UTC, audiodude commented on openapi.yml
> +      operationId: getResponse
getResponse is way too generic. How about 'createSimpleList'?

2021-07-02 22:28 UTC, audiodude commented on openapi.yml
> +        200:
You're returning 400 if the params are invalid right? You need to document that here.

2021-07-02 22:30 UTC, audiodude commented on wp1-frontend/src/components/CreateSimpleList.vue
>    name: 'MyLists',
I believe that change was made erroneously. This is the page for creating simple lists right? The name of the file is `CreateSimpleList.vue`. The other page is `MyLists.vue` right?

2021-07-02 22:31 UTC, audiodude commented on wp1/web/selection.py
> +  response = flask.request.get_json()
This is not a response, it is a request, so calling it response is very confusing. Either way `data` or simply `json` would be a better name.

2021-07-03 18:40 UTC, audiodude requested changes
Very close to being done. I actually patched this PR and it worked rather well. Thanks again!

2021-07-03 18:40 UTC, audiodude commented on openapi.yml
> +  - url: http://localhost:5000/v1
Please change these back.

2021-07-03 18:40 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +  it('wiki projects displayed', () => {
This one was actually fine "It displays wiki projects" is a good sounding sentence.

2021-07-03 18:40 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +  it('validates list name on loosing focus', () => {
s/loosing/losing/

2021-07-03 18:40 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +  it('validates textbox on loosing focus', () => {
s/loosing/losing/

2021-07-03 18:40 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +  it('textbox displayed with invalid article names', () => {
It 'displays a textbox with invalid article names'

2021-07-03 18:40 UTC, audiodude commented on wp1/web/sites.py
> +  print(sites_data)
nit: remove print.

2021-07-03 19:11 UTC, mahakporwal02 commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +      'Statue_of_Liberty#'
Maybe when we send response `(success=false)` to frontend we should remove the `underscores`?

2021-07-03 19:14 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +      'Statue_of_Liberty#'
The thing is, at that point we won't know if the user originally typed the underscores or if we added them, so if we universally remove them, we won't be doing the right thing in all cases.

It seems like if we wanted to display the original item, we'd have to change the `validate_list` method to check for forbidden characters before it transforms the spaces. Do you want to file an issue for that?

2021-07-03 19:15 UTC, audiodude approved these changes
LGTM

2021-07-03 19:16 UTC, merged