added auth to selections
openzim/wp1 pull request #387
Opened 2021-07-07 20:29 UTC by mahakporwal02

This fixes #386

2021-07-09 00:36 UTC, audiodude requested changes
Good work, just a few minor things to change.

2021-07-09 00:36 UTC, audiodude commented on wp1-frontend/cypress/fixtures/failure.json
> +{
I would name this file `save_list_failure` because there might be other failure fixtures in the future.

2021-07-09 00:36 UTC, audiodude commented on wp1-frontend/cypress/fixtures/success.json
> +{ "success": true, "items": {} }
Same thing: `save_list_success`.

2021-07-09 00:36 UTC, audiodude commented on wp1-frontend/cypress/integration/createList_page.spec.js
> +  it('opens login page', () => {
I would put all of the above tests in a `describe('when the user is logged in', ...` block, so that you could put the cy.intercept for identify in a beforeEach and not have to repeat it every time. Then put this one in a `describe('when the user is not logged in', ...)` block.

2021-07-09 00:36 UTC, audiodude commented on wp1-frontend/src/components/loginRequired.vue
> +  name: 'loginRequired',
Components should be upper camel case: `LoginRequired`. Be sure to rename the file too.

2021-07-09 00:36 UTC, audiodude commented on wp1-frontend/src/components/loginRequired.vue
> +    <h2 class="row justify-content-center pt-5">
Shouldn't this be used on the ManualUpdate page too?

2021-07-09 12:41 UTC, mahakporwal02 commented on wp1-frontend/src/components/loginRequired.vue
> +    <h2 class="row justify-content-center pt-5">
Are you talking about the `LoginRequired` component?

2021-07-09 18:05 UTC, audiodude commented on wp1-frontend/src/components/loginRequired.vue
> +    <h2 class="row justify-content-center pt-5">
Yes, just wondering because I don't see any changes to the ManualUpdate component and I assume it should be using the same LoginRequired component.

2021-07-09 18:34 UTC, mahakporwal02 commented on wp1-frontend/src/components/loginRequired.vue
> +    <h2 class="row justify-content-center pt-5">
But I have made changes to `Update Page` component. 
And I am using `LoginRequired` component only.

2021-07-09 21:54 UTC, audiodude commented on wp1-frontend/src/components/loginRequired.vue
> +    <h2 class="row justify-content-center pt-5">
Good point. I only counted two usages and forgot the page was called UpdatePage. I guess the missing usage is on MyLists?

2021-07-09 22:00 UTC, mahakporwal02 commented on wp1-frontend/src/components/loginRequired.vue
> +    <h2 class="row justify-content-center pt-5">
Should I add it?
I purposely didn't add it

2021-07-09 22:03 UTC, audiodude commented on wp1-frontend/src/components/loginRequired.vue
> +    <h2 class="row justify-content-center pt-5">
Can you expand on your reasoning for not adding it?

2021-07-10 12:02 UTC, mahakporwal02 commented on wp1-frontend/src/components/loginRequired.vue
> +    <h2 class="row justify-content-center pt-5">
Sorry I got confused with the other PR.
I'll fix it.

2021-07-10 16:45 UTC, audiodude approved these changes
LGTM

2021-07-10 16:45 UTC, merged