Persist simple lists
openzim/wp1 pull request #389
Opened 2021-07-10 19:11 UTC by audiodude

This rather large PR includes the logic that is called from the backend simple list "create" endpoint. The new logic method `persist_simple_list` handles storing a simple list selection in both the database (for its metadata) and the backend s3 storage (for its article list). Includes tests for the endpoint as well as the logic methods and the model methods.

2021-07-10 19:17 UTC, audiodude commented
@mahakporwal02 sorry for the rather large PR!

2021-07-11 21:37 UTC, mahakporwal02 requested changes
Some changes I could figure out. Will you also add developers overlay afterwards?

2021-07-11 21:37 UTC, mahakporwal02 commented on wp1/logic/selection.py
> +  wp10db.commit()
Shouldn't this line should be above return statement?

2021-07-11 21:37 UTC, mahakporwal02 commented on wp1/web/app.py
> +  app.register_blueprint(selection, url_prefix='/v1/selection')
Blueprint has been registered twice.

2021-07-11 21:37 UTC, mahakporwal02 commented on wp1/web/selection.py
> +  logic_selection.persist_simple_list(wp10db, s3, list_name, user_id, project,
Shouldn't this should be under try catch?

2021-07-12 00:59 UTC, audiodude commented
Thanks for the review! I'm actually going to abandon this PR based on the comments on #370 and #374. We need a different schema for list builders/selections and a more generalized way of "materializing" built lists to the storage backend as selections.

2021-07-12 00:59 UTC, closed without merging