AbstractBuilder with tests
openzim/wp1 pull request #396
Opened 2021-07-29 04:12 UTC by audiodude

Includes database migration to add b_model to builders table and necessary test schema files.

This code doesn't do much on it's own, but provides an interface for a subclass to implement the not-implemented build method. Given such an implementation, and when passed a valid builder and a content type, the AbstractBuilder materialize method will build the selection from the builder and store the resultant selection list in s3. It will also save a Selection record in the WP 1.0 database for the selection list.

2021-07-30 19:58 UTC, mahakporwal02 requested changes
Conceptually LGTM.

2021-07-30 19:58 UTC, mahakporwal02 commented on wp1/selection/abstract_builder_test.py
> +  def test_materialize_selection_updated_at(self, mock_utcnow):
`mock_utcnow` is not being used. It has already been mocked in above line.

2021-07-30 19:58 UTC, mahakporwal02 commented on wp1/selection/abstract_builder_test.py
> +  def test_materialize_selection_id(self, mock_setid):
`mock_setid` is not being used.

2021-07-30 19:58 UTC, mahakporwal02 commented on wp1/selection/abstract_builder.py
> +    selection.data = self.build(content_type, **params)
`selection.data` is not defined in selection model.

2021-07-31 20:54 UTC, audiodude commented on wp1/selection/abstract_builder_test.py
> +  def test_materialize_selection_updated_at(self, mock_utcnow):
I tried leaving out the parameter, but I get an error because the `@patch` decorator injects the patched value as a parameter even if you don't use it.

2021-07-31 20:54 UTC, audiodude commented on wp1/selection/abstract_builder_test.py
> +  def test_materialize_selection_id(self, mock_setid):
Same thing here.

2021-07-31 20:58 UTC, audiodude commented on wp1/selection/abstract_builder.py
> +    selection.data = self.build(content_type, **params)
Done

2021-08-01 19:50 UTC, mahakporwal02 approved these changes
LGTM

2021-08-01 19:55 UTC, merged