added simple list builder module
openzim/wp1 pull request #398
Opened 2021-08-02 17:41 UTC by mahakporwal02

This fixes #395.

2021-08-02 18:13 UTC, audiodude requested changes
As part of moving validate_list into the simple_builder.py file, you should move the tests as well. And also add tests for build(). Thanks!

2021-08-02 18:13 UTC, audiodude commented on wp1/selection/simple_builder.py
> +    valid_names, invalid_names, forbiden_chars = validate_list(params['list'])
There is no need to have validate_list be it's own function in its own module. It's only used for validating Simple builders like this one. For now, you can move the function to this module as `_validate_list` and call it the way you are doing. But eventually, the validate method on SimpleBuilder should ***be*** that function, if that makes sense.

2021-08-02 18:13 UTC, audiodude commented on wp1/selection/simple_builder.py
> +    return '\n'.join(params['list']).encode('utf-8')
We should validate that the params contain a 'list' entry. We might also want to validate that the params don't contain any **other** entries, to protect against accidentally calling the SimpleBuilder with params that looks similar to, but aren't quite, SimpleBuilder params.

For now, you can simply raise `ValueError`, but we should create an issue for tracking a custom Exception hierarchy that we can catch for explicitly.

2021-08-02 18:13 UTC, audiodude commented on wp1/selection/simple_builder.py
> +    valid_names, invalid_names, forbiden_chars = validate_list(params['list'])
We should validate that 'list' exists here too, see comment above.

2021-08-03 16:44 UTC, audiodude requested changes
Good work on moving the function. There are a few subtle cases that I think we should take care of.

2021-08-03 16:44 UTC, audiodude commented on wp1/selection/simple_builder_test.py
> +    self.assertRaises(KeyError)
You need to use a context manager here:

```
with self.assertRaises(KeyError):
   code_that_raises()
```

Otherwise nothing is being asserted.

2021-08-03 16:44 UTC, audiodude commented on wp1/selection/simple_builder.py
> +      KeyError('Incorrect params present')
You need to actually raise the exception:

```
raise ValueError('Missing required param: list')
```

Let's not use KeyError, that has a very specific meaning around dictionaries. It also is very nice to specify the actual key/param that caused the error.

2021-08-03 16:44 UTC, audiodude commented on wp1/selection/simple_builder.py
> +    ValueError('Unwanted params present')
s/Unwanted/Additional unnecessary/

2021-08-03 16:44 UTC, audiodude commented on wp1/selection/simple_builder.py
> +      forbiden_chars.insert(
Why `insert` and not just `append`?

2021-08-03 16:44 UTC, audiodude commented on wp1/selection/simple_builder.py
> +    forbiden_chars = []
Just realized that "forbidden" is spelled wrong throughout this function. Please fix.

2021-08-03 16:44 UTC, audiodude commented on wp1/selection/simple_builder.py
> +    valid_names, invalid_names, forbiden_chars = self._validate_list(**params)
`forbiden_chars` is spelled wrong here too.

2021-08-03 16:44 UTC, audiodude commented on wp1/selection/simple_builder.py
> +    return (valid_names, invalid_names, forbiden_chars)
The last value of the tuple should be full, English error messages like:

['The list contained the following invalid characters: # <', 'The list contained an item longer than 256 bytes', 'The list did not satisfy some other foo bar requirement']

2021-08-03 16:44 UTC, audiodude commented on wp1/selection/simple_builder.py
> +class SimpleBuilder(AbstractBuilder):
Please move this file to `wp1/selection/models/simple.py`

2021-08-03 16:44 UTC, audiodude commented on wp1/selection/simple_builder_test.py
> +class ValidateArticleNameTest(unittest.TestCase):
s/ValidateArticleNameTest/SimpleBuilderTest/

2021-08-03 16:44 UTC, audiodude commented on wp1/selection/simple_builder.py
> +  def build(self, content_type, **params):
Currently, this ignores the content_type parameter. Since it currently can only output `text/tab-separated-values`, it should raise a `ValueError` if the content_type doesn't match that.

2021-08-03 16:44 UTC, audiodude commented on wp1/selection/simple_builder.py
> +      if 'list' in params.keys():
nit: I don't think you need .keys() here.

2021-08-03 16:44 UTC, audiodude commented on wp1/selection/simple_builder.py
> +  def _validate_list(self, **params):
Did you remove this function from the selection module? I don't see that change. It's no longer needed there.

2021-08-03 21:21 UTC, mahakporwal02 commented
@audiodude  Tests are failing because I have not made changes in `wp1.web.selection.py` yet. The route `/selection/simple` calls `validate_list` func which I have removed in the last commit.
Should I make changes there now?

2021-08-03 22:56 UTC, audiodude requested changes
> @audiodude Tests are failing because I have not made changes in `wp1.web.selection.py` yet. The route `/selection/simple` calls `validate_list` func which I have removed in the last commit.
> Should I make changes there now?

Yes, definitely.

2021-08-03 22:56 UTC, audiodude commented on wp1/selection/models/simple_builder_test.py
> +    actual = simple_test_builder.build('text/tab-separated-values',
nit: you don't need this line for this test.

2021-08-03 23:01 UTC, audiodude requested changes
A couple more things

2021-08-03 23:01 UTC, audiodude commented on wp1/selection/models/simple_builder.py
> +from wp1.constants import CONTENT_TYPE_TO_EXT
I don't think you need this import.

2021-08-03 23:01 UTC, audiodude commented on wp1/selection/models/simple_builder.py
> +    return self._validate_list(**params)
Since this method is now just calling the _validate_list function, can you move the body of _validate_list here and get rid of the extra function?

2021-08-04 16:25 UTC, audiodude commented on wp1/web/selection.py
> +  valid_names, invalid_names, forbiden_chars = simple_builder.validate(**params)
s/forbiden/forbidden/

2021-08-04 16:25 UTC, audiodude commented on wp1/web/selection_test.py
> +          'forbiden_chars': [
Looks like 'forbiden' made it into the API? Can you change it here and in openapi.yml?

2021-08-04 16:29 UTC, audiodude requested changes
Very close to being done, good work.

2021-08-04 16:29 UTC, audiodude commented on wp1/web/selection_test.py
> +          'forbiden_chars': [
Actually, this should be `errors` now, not `forbiden_chars`. Can you file an issue so that they're displayed appropriately on the frontend?

2021-08-04 17:04 UTC, audiodude commented
Your code coverage is failing for the same reason mine was on the last PR: the `wp1/selection/models` directory needs an empty `__init__.py` file in it so that it can be considered a module and nosetests can find the tests.

2021-08-04 19:50 UTC, audiodude requested changes

2021-08-04 19:50 UTC, audiodude commented on wp1/web/selection.py
> +  valid_names, invalid_names, forbiden_chars = simple_builder.validate(**params)
Please fix.

2021-08-04 20:10 UTC, audiodude approved these changes
LGTM

2021-08-04 20:10 UTC, merged