list selections displayed in the form of table
openzim/wp1 pull request #437
Opened 2021-08-25 18:47 UTC by mahakporwal02

This fixes #433.

2021-08-28 03:49 UTC, audiodude requested changes
A few things that need to be cleaned up here.

2021-08-28 03:49 UTC, audiodude commented on wp1-frontend/src/components/MyLists.vue
> +      console.log(this.list);
nit: remove console.log

2021-08-28 03:49 UTC, audiodude commented on wp1-frontend/src/components/MyLists.vue
> +              <td>{{ item.name }}</td>
It would be better if the things that were the same for each builder were set with rowspan=2 instead of being repeated.

2021-08-28 03:49 UTC, audiodude commented on wp1-frontend/src/components/MyLists.vue
> +                  >Download {{ selection.content_type }}</a
You're showing the content-type again when it should be the extension.

2021-08-28 03:49 UTC, audiodude commented on wp1-frontend/src/components/MyLists.vue
> +                <a class="btn btn-primary mb-2 mr-2" download
You need the href of the button to be the download URL.

2021-08-28 03:49 UTC, audiodude commented on wp1/logic/builder.py
> +          # 'created_at': datetime.datetime.strptime(value['created_at'], TS_FORMAT_WP10),
The fact that you're getting a ValueError with strptime might mean that you never applied the database migrations that turned the timestamps from `BINARY(20)` to `BINARY(14)`, which would explain the extra null values at the end of the string.

But either way, passing a `datetime.datetime` to a dictionary that is going to be serialized to JSON isn't going to work.

2021-09-03 01:19 UTC, audiodude requested changes
Just a few more comments

2021-09-03 01:19 UTC, audiodude commented on wp1-frontend/src/components/MyLists.vue
> +              <td v-if="item.selections.length">
I think you need the `<td>`s that represent all of the other fields, so that the rowspan will work. You should create cypress fixtures with:

1. A builder with no selections
2. A builder with one selection
3. A builder with multiple selections

And then write tests and verify they all look correct.

2021-09-03 01:19 UTC, audiodude commented on wp1/logic/builder.py
> +            'created_at': b['b_created_at'].decode('utf-8'),
You had the right idea before, in general. We shouldn't display "20210102105523" as a big garbled string to the user. We should display something that makes more sense.

Maybe you can make a utility function called `wp10_timestamp_human_readable(timestamp_str)` that takes in these strings, parses them according to TS_FORMAT_WP10 and returns a human readable value.

2021-09-05 19:45 UTC, audiodude commented on wp1-frontend/src/components/MyLists.vue
> +            <tr>
Maybe add a class to this td, `class="selection-row"` and then style it with `line-height: 2em` so that the buttons line up better with the text?

2021-09-05 19:45 UTC, audiodude commented on wp1-frontend/src/components/MyLists.vue
> +            <tr
Make this `selection-row` too.

2021-10-15 13:21 UTC, kelson42 commented
@mahakporwal02 Would be really nice if you could next help to move this PR forward.

2022-01-19 07:40 UTC, kelson42 commented
@audiodude Still plans to merge this PR?

2022-01-19 18:07 UTC, audiodude commented
@kelson42 yes I can look at patching/fixing/merging.

2022-01-23 22:40 UTC, audiodude commented
Superseeded by #449.

2022-01-23 22:40 UTC, closed without merging