UI for requesting ZIM file for WP1 Selection
openzim/wp1 pull request #597
Opened 2023-03-30 00:51 UTC by audiodude

This PR provides the frontend UI, written in Vue, to allow a user to create a ZIM file from their WP1 Selections. It provides a new page where the user can enter the `Description` and `LongDescription` of the ZIM file, request its creation, monitor its progress, and download the ZIM file when it is ready. The ZIM file also has an updated time which is displayed in the 'My Selections' table view, where the ZIM file can also be downloaded.

2023-04-04 11:16 UTC, rgaudin requested changes
Not sure if it's already released or not but main mwoffliner has characters limits for description and longdescription.

2023-04-04 11:16 UTC, rgaudin commented on wp1/zimfarm.py
> +              if long_description else 'ZIM file created from a WP1 Selection',
I am not sure if `LongDescription` is supposed to complement or replace `Description` in a (reader) context where we have both –I've asked @kelson42 for clarification as [the spec](https://wiki.openzim.org/wiki/Metadata) is not definitive.
It if is not a replacement, using the same string twice would not make sense

2023-04-04 11:16 UTC, rgaudin commented on wp1-frontend/src/components/ZimFile.vue
> +              v-model="description"
mwoffliner now doesn't accepts description that are above 80 chars. You should probably prevent that as soon as it's entered

2023-04-04 11:16 UTC, rgaudin commented on wp1-frontend/src/components/ZimFile.vue
> +              v-model="longDescription"
mwoffliner now doesn't accepts longdescription that are above 4,000 chars as well

2023-04-04 11:56 UTC, rgaudin commented on wp1/zimfarm.py
> +              if long_description else 'ZIM file created from a WP1 Selection',
Got the answer ; `LongDescription` complements `Description`.

2023-04-05 02:02 UTC, audiodude commented on wp1-frontend/src/components/MyLists.vue
> +              <td v-if="item.s_zim_file_url && !isPending(item)">
If the user has an existing ZIM file, but the selection materialization is pending (`isPending(item)`) we should not show the ZIM download link, that's what this is for.

2023-04-05 02:03 UTC, audiodude commented on wp1-frontend/src/components/MyLists.vue
> +              <td v-if="item.s_zim_file_url && !isPending(item)">
Same thing, don't show the date of an existing ZIM file when selection materialization is pending.

2023-04-05 02:05 UTC, audiodude commented on wp1-frontend/src/components/MyLists.vue
> +              <td v-else-if="!isPending(item) && !hasSelectionError(item)">
Again, you shouldn't be able to "Create ZIM" unless the materialization is done.

2023-04-05 02:09 UTC, audiodude commented on wp1/zimfarm.py
> +              if long_description else 'ZIM file created from a WP1 Selection',
If we're using a default value, it's possible that the user has filled in one of `Description` and `LongDescription` anyways, so it won't be redundant.

Even if they haven't filled in either, we don't have anything meaningful to say in the `LongDescription` for a default value, except a slightly reworded and more verbose version of what we already have. In this case, I'd argue it's better to have them be redundant so that the user will remember that they didn't put anything there.

WDYT @kelson42 ?

2023-04-05 02:12 UTC, audiodude commented on wp1-frontend/src/components/ZimFile.vue
> +              v-model="description"
Done

2023-04-05 02:12 UTC, audiodude commented on wp1-frontend/src/components/ZimFile.vue
> +              v-model="longDescription"
Done

2023-04-05 02:13 UTC, audiodude commented on wp1/logic/builder.py
> +def _get_selection_data(b):
Done.

2023-04-05 06:48 UTC, kelson42 commented on wp1/zimfarm.py
> +              if long_description else 'ZIM file created from a WP1 Selection',
I slightly jump in the discussion, please excuse me if I don't get the point.

First they should not be default value as far as I can figure out, once we have a form to fil the Metadata. User has to put a `Title` and a `Description`. Then `LongDescription` is optional.

Maybe it helps to better undersant the purpose if I say that `Description` should be the motto or slogan of the content and `LongDescription` the freetext description of the content.

2023-04-05 07:33 UTC, rgaudin commented on wp1/zimfarm.py
> +              if long_description else 'ZIM file created from a WP1 Selection',
> Even if they haven't filled in either, we don't have anything meaningful to say in the `LongDescription` for a default value, except a slightly reworded and more verbose version of what we already have. In this case, I'd argue it's better to have them be redundant so that the user will remember that they didn't put anything there.

@kelson42 already replied. `LongDescription` should not be set at all if the user didn't provide it (so no `""` neither). As for `Description`, it is mandatory that the user sets it. As you said, it's obviously not possible to set a meaningful generic one, so leave it to the user by forcing him to set it.

2023-04-07 01:22 UTC, audiodude commented on wp1/zimfarm.py
> +              if long_description else 'ZIM file created from a WP1 Selection',
Okay I've made the `Description` required.

2023-04-07 07:18 UTC, rgaudin approved these changes

2023-04-07 16:21 UTC, merged